define(['backbone'], 
function(Backbone){

	var EventDispatcher = function(){}
	
	_.extend(EventDispatcher.prototype, Backbone.Events, {
		ADVERTISER_SAVE : "ADVERTISER_SAVE",
		ACTIVITY_SAVE : "ACTIVITY_SAVE",
		ACTIVITY_TAG_CREATE : "ACTIVITY_TAG_CREATE",
		CAMPAIGN_SAVE : "CAMPAIGN_SAVE",
		IMPRESSION_TAG_SAVE : "IMPRESSION_TAG_SAVE",
		DATAPARTNER_SAVE : "DATAPARTNER_SAVE",
		DATAPARTNERMODEL_SAVE: "DATAPARTNERMODEL_SAVE",
		DATASOURCE_SAVE : "DATASOURCE_SAVE",
		EXPORT_SECTION_ENABLED : "EXPORT_SECTION_ENABLED",
		VISITOR_KEYS : "VISITOR_KEYS",
		ITEM_CHECKED : "ITEM_CHECKED",
		ITEM_UNCHECKED : "ITEM_UNCHECKED",
		SEAT_ITEM_SET : "SEAT_ITEM_SET",
		SELECT_ALL : "SELECT_ALL",
		CC_CREATE_EDIT_SAVE: "CC_CREATE_EDIT_SAVE",
		DSP_SAVE : "DSP_SAVE",
		DATA_LEDGER: "DATA_LEDGER"
	});
	
	return new EventDispatcher();
});
